### ISSUE TITLE
Please create missing tags

### ISSUE THREAD

**Issue by nuzil** [risscsolutions/printformer-magento-2#1]
I see that extension is already on version 100.8.63
https://github.com/risscsolutions/printformer-magento-2/commit/8d6ee69ed0971bdefd199898ba7cbe75e21fd4ed

But there are no respective tags. 
Can you please define new versions, so we can install it via composer.

Thanks

**Comment by rissc** [comment]
@nuzil done
https://github.com/risscsolutions/printformer-magento-2/commit/9fd36f2c8164800825f916f7480f4ba6e7a87b97
